use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::time::Duration;

use axum::{
    extract::{Path, State},
    http::StatusCode,
    Extension, Json,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tokio::sync::Mutex;

use surrealdb::types::SurrealValue;

use eck_core::auth::Claims;
use eck_core::db::SurrealDb;
use eck_core::models::i18n_label::label_record_id;

use crate::AppState;

/// Default Gemini model for label translation — same lightweight model the
/// content-translation queue uses (`GEMINI_TRANSLATE_MODEL` overrides both).
const DEFAULT_TRANSLATE_MODEL: &str = "gemini-3.5-flash-lite";
/// Keys per Gemini call in the add-language job. Small enough to stay well under
/// the output-token ceiling, large enough to keep the call count (and cost) low.
const LANG_CHUNK: usize = 50;
/// Default daily ceiling on label-translation Gemini calls (runaway guardrail);
/// override with `I18N_LANG_DAILY_CAP`. One full language is only ~20-30 calls,
/// so the default comfortably covers deliberate admin use while capping abuse.
const DEFAULT_LANG_DAILY_CAP: u32 = 2000;

/// `(epoch-day, calls-today)` for the label-translation daily cap. Process-global,
/// reset lazily at UTC midnight. A plain `std::sync::Mutex` is fine — the critical
/// section is tiny and never held across an `.await`.
static LANG_CAP: std::sync::Mutex<(i64, u32)> = std::sync::Mutex::new((0, 0));

/// UI-label seed baked in at build time. Generated by `tools/gen_i18n_seed.mjs`
/// from the JS locale files; regenerate + recommit after editing any locale.
/// SurrealDB is the runtime source of truth, but the seed OWNS its rows: on
/// startup [`seed_i18n_labels`] inserts missing rows AND updates rows whose
/// value drifted from the current seed — only rows marked `src: 'user'` are
/// preserved (see the fn doc for why plain insert-if-missing went stale).
const I18N_SEED_JSON: &str = include_str!("../../assets/i18n_seed.json");

/// One row of the generated seed: the runtime key, its language, and the value.
#[derive(Debug, Clone, Deserialize)]
pub struct SeedEntry {
    pub key: String,
    pub lang: String,
    pub value: String,
}

/// Parse the seed JSON (a flat array of `{key, lang, value}`).
fn parse_seed(raw: &str) -> Result<Vec<SeedEntry>, serde_json::Error> {
    serde_json::from_str(raw)
}

/// Collapse the seed to one entry per deterministic record id (first wins), so
/// a duplicate `(lang, key)` in the source can't fight itself during INSERT.
/// Returns `(record_id, entry)` pairs — the record id is the DB row key.
fn dedup_seed(entries: Vec<SeedEntry>) -> Vec<(String, SeedEntry)> {
    let mut seen: HashSet<String> = HashSet::new();
    let mut out: Vec<(String, SeedEntry)> = Vec::with_capacity(entries.len());
    for e in entries {
        let rid = label_record_id(&e.lang, &e.key);
        if seen.insert(rid.clone()) {
            out.push((rid, e));
        }
    }
    out
}

/// The set of languages the startup seed is allowed to insert, from `I18N_LANGS`
/// (comma-separated, e.g. `"en,de"`). Unset/empty → `None` (seed every bundled
/// language — the backward-compatible default). Set → those codes PLUS `en`,
/// which is ALWAYS seeded because it is the fallback/base every other language
/// resolves against. Codes are normalized to their 2-letter primary subtag.
fn seed_lang_allowset() -> Option<HashSet<String>> {
    let raw = std::env::var("I18N_LANGS").unwrap_or_default();
    if raw.trim().is_empty() {
        return None;
    }
    let mut set: HashSet<String> = raw
        .split(',')
        .filter_map(|s| eck_core::i18n::normalize_lang(s))
        .collect();
    set.insert("en".to_string()); // base/fallback — never gated out
    Some(set)
}

/// One existing `i18n_label` row as the seeder sees it: deterministic record
/// id, current value, and provenance (`src`). Legacy rows predate `src`.
#[derive(Debug, Deserialize, SurrealValue)]
struct ExistingLabel {
    rid: String,
    value: Option<String>,
    src: Option<String>,
}

/// Diff the baked-in seed against the DB. Returns `(inserts, updates,
/// kept_user)`:
/// - missing row → insert;
/// - row whose value differs from the seed → update, UNLESS `src == 'user'`
///   (an explicit edit is respected and counted in `kept_user`);
/// - row matching the seed → untouched (no write, no stamp).
fn seed_actions(
    rows: &[(String, SeedEntry)],
    existing: &HashMap<String, (Option<String>, Option<String>)>,
) -> (Vec<Value>, Vec<Value>, usize) {
    let mut inserts = Vec::new();
    let mut updates = Vec::new();
    let mut kept_user = 0usize;
    for (rid, e) in rows {
        match existing.get(rid) {
            None => inserts.push(json!({ "rid": rid, "key": e.key, "lang": e.lang, "value": e.value })),
            Some((value, src)) => {
                if value.as_deref() == Some(e.value.as_str()) {
                    continue;
                }
                if src.as_deref() == Some("user") {
                    kept_user += 1;
                    continue;
                }
                updates.push(json!({ "rid": rid, "value": e.value }));
            }
        }
    }
    (inserts, updates, kept_user)
}

/// Startup seeding for `i18n_label`. Parses the baked-in seed once and syncs
/// the DB to it: missing rows are INSERTed, rows whose value drifted from the
/// current seed are UPDATEd (stamped `src: 'seed'`), rows marked `src: 'user'`
/// are never touched. Wire this once, early in startup, after the Zone-2
/// tables are ensured.
///
/// Why not plain insert-if-missing: there is no label-edit API, so under the
/// old "existing rows are never touched" rule every node's labels froze at
/// whatever binary first seeded its DB — and the client-side DB overlay then
/// shadowed every later string change (fleet-wide raw `{placeholder}`
/// artifacts, 2026-08-04). Rows the seed doesn't know (customer-added
/// languages from the Gemini translator) have no seed entry and are never
/// candidates. `i18n_label` is not in `SYNC_ENTITY_TYPES`, so this heals each
/// node locally on its first restart with a newer binary.
///
/// `I18N_LANGS` gates WHICH bundled languages are seeded (see
/// [`seed_lang_allowset`]) — ship English (or a small configured set) and let
/// customers add further languages at runtime via `POST /api/admin/i18n/languages`.
pub async fn seed_i18n_labels(db: &SurrealDb) -> Result<(), String> {
    // Schemaless table (idempotent). The row id is deterministic, so the table
    // needs no unique index — duplicate (lang,key) simply address one row.
    let _ = db
        .query("DEFINE TABLE IF NOT EXISTS i18n_label SCHEMALESS;")
        .await
        .map_err(|e| e.to_string())?;

    let entries = parse_seed(I18N_SEED_JSON).map_err(|e| format!("i18n seed parse: {e}"))?;
    let rows = dedup_seed(entries);

    // Language gate: `I18N_LANGS` unset → seed all bundled languages; set → only
    // the listed ones (+ en). Runs BEFORE the missing-row diff so gated-out
    // languages are never inserted, but any that already exist stay untouched.
    let allow = seed_lang_allowset();
    let rows: Vec<(String, SeedEntry)> = match &allow {
        Some(set) => rows.into_iter().filter(|(_, e)| set.contains(&e.lang)).collect(),
        None => rows,
    };
    if let Some(set) = &allow {
        let mut langs: Vec<&String> = set.iter().collect();
        langs.sort();
        tracing::info!("i18n seed gated to I18N_LANGS: {:?}", langs);
    }
    let total = rows.len();

    // One query pulls every existing row's id + value + provenance; the seed
    // is diffed against it in memory (see `seed_actions`).
    let existing_rows: Vec<ExistingLabel> = db
        .query("SELECT record::id(id) AS rid, value, src FROM i18n_label")
        .await
        .map_err(|e| e.to_string())?
        .take(0)
        .map_err(|e| e.to_string())?;
    let existing: HashMap<String, (Option<String>, Option<String>)> = existing_rows
        .into_iter()
        .map(|r| (r.rid, (r.value, r.src)))
        .collect();

    let (inserts, updates, kept_user) = seed_actions(&rows, &existing);
    let (to_insert, to_update) = (inserts.len(), updates.len());

    // Bulk CREATE in chunks. Each chunk is a single FOR statement → one
    // transaction (one fsync batch) instead of thousands of round-trips. The
    // deterministic id via `type::record` makes each row addressable + unique.
    // (SurrealDB 3 renamed `type::thing` → `type::record`; same table+id form.)
    for chunk in inserts.chunks(500) {
        db.query(
            "FOR $r IN $rows { \
                 CREATE type::record('i18n_label', $r.rid) CONTENT { \
                     key: $r.key, lang: $r.lang, value: $r.value, src: 'seed', updated_at: time::now() \
                 }; \
             }",
        )
        .bind(("rows", chunk.to_vec()))
        .await
        .map_err(|e| e.to_string())?
        .check()
        .map_err(|e| e.to_string())?;
    }

    // Same batching for value updates — rows the seed owns that drifted (old
    // seed generations, or a locale edit shipped in a newer binary).
    for chunk in updates.chunks(500) {
        db.query(
            "FOR $r IN $rows { \
                 UPDATE type::record('i18n_label', $r.rid) SET \
                     value = $r.value, src = 'seed', updated_at = time::now(); \
             }",
        )
        .bind(("rows", chunk.to_vec()))
        .await
        .map_err(|e| e.to_string())?
        .check()
        .map_err(|e| e.to_string())?;
    }

    tracing::info!(
        "i18n labels: inserted {}, updated {}, user-kept {} of {}",
        to_insert, to_update, kept_user, total
    );
    Ok(())
}

/// GET /api/i18n/dict/:lang — PUBLIC (no auth): the login page needs labels
/// before a token exists, and labels aren't secrets. Returns every label for
/// one language as a flat `{ "<ns>.<key>": value }` map in a SINGLE DB query.
/// Unknown / empty lang → `{ success:true, labels:{}, count:0 }`.
pub async fn dict(
    Path(lang): Path<String>,
    State(state): State<Arc<AppState>>,
) -> (StatusCode, Json<Value>) {
    let lang = lang.trim().to_string();
    if lang.is_empty() {
        return (
            StatusCode::OK,
            Json(json!({ "success": true, "lang": lang, "labels": {}, "count": 0 })),
        );
    }

    let result: Result<Vec<Value>, _> = state
        .db
        .query("SELECT key, value FROM i18n_label WHERE lang = $lang")
        .bind(("lang", lang.clone()))
        .await
        .and_then(|mut r| r.take(0));

    let rows = match result {
        Ok(rows) => rows,
        Err(e) => {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "success": false, "error": e.to_string() })),
            );
        }
    };

    let mut labels = serde_json::Map::new();
    for row in &rows {
        if let (Some(k), Some(v)) = (
            row.get("key").and_then(|x| x.as_str()),
            row.get("value").and_then(|x| x.as_str()),
        ) {
            labels.insert(k.to_string(), Value::String(v.to_string()));
        }
    }
    let count = labels.len();

    (
        StatusCode::OK,
        Json(json!({ "success": true, "lang": lang, "labels": labels, "count": count })),
    )
}

/// GET /api/i18n/languages — distinct UI languages spoken by active users,
/// ordered by frequency DESC then alphabetically. Behind `auth_middleware`
/// only (NOT admin-only): the kiosk observer token must be able to read this
/// so the kiosk language button can populate itself.
///
/// The language set is derived from the users table — there is NO hardcoded
/// language list in committed code, keeping the app company-generic.
pub async fn languages(
    Extension(_claims): Extension<Claims>,
    State(state): State<Arc<AppState>>,
) -> (StatusCode, Json<Value>) {
    let result: Result<Vec<Value>, _> = state
        .db
        .query(
            "SELECT preferredLanguage, languages FROM user \
             WHERE isActive = true AND deleted_at IS NONE",
        )
        .await
        .and_then(|mut r| r.take(0));

    let rows = match result {
        Ok(rows) => rows,
        Err(e) => {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "success": false, "error": e.to_string() })),
            );
        }
    };

    // Build per-user raw code lists: preferredLanguage plus every `languages`
    // entry. Normalization + dedup + frequency ordering happen in core.
    let per_user: Vec<Vec<String>> = rows
        .iter()
        .map(|row| {
            let mut codes: Vec<String> = Vec::new();
            if let Some(pref) = row.get("preferredLanguage").and_then(|v| v.as_str()) {
                codes.push(pref.to_string());
            }
            if let Some(arr) = row.get("languages").and_then(|v| v.as_array()) {
                for item in arr {
                    if let Some(s) = item.as_str() {
                        codes.push(s.to_string());
                    }
                }
            }
            codes
        })
        .collect();

    let languages = eck_core::i18n::aggregate_languages(&per_user);

    // Languages that actually EXIST in the label dictionary (Zone-2 `i18n_label`),
    // so the frontend can grow its available-locale set to include customer-added
    // languages. `count()` forces the GROUP BY aggregate → one row per distinct
    // lang (canonical v3 form; avoids the "SELECT DISTINCT silently returns []"
    // pitfall). Independent of the users-languages union above, which stays the
    // kiosk cycle order.
    let dict_rows: Vec<Value> = state
        .db
        .query("SELECT lang, count() AS n FROM i18n_label GROUP BY lang")
        .await
        .and_then(|mut r| r.take(0))
        .unwrap_or_default();
    let mut dict_languages: Vec<String> = dict_rows
        .iter()
        .filter_map(|r| r.get("lang").and_then(|v| v.as_str()).map(String::from))
        .collect();
    dict_languages.sort();
    dict_languages.dedup();

    (
        StatusCode::OK,
        Json(json!({
            "success": true,
            "languages": languages,
            "dict_languages": dict_languages,
        })),
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Customer-addable languages: machine-translate the whole English label set into
// a new language at runtime and store the rows in `i18n_label` (same
// deterministic id scheme as the seed → idempotent + re-runnable).
// ─────────────────────────────────────────────────────────────────────────────

/// In-memory status of one add-language translation job. Serialized to the
/// status endpoint. PROCESS-LOCAL (not mesh-synced): a fresh boot resets it to
/// `idle`, which is correct — the `i18n_label` rows are the durable result, this
/// only tracks an in-flight run.
#[derive(Clone, Debug, Serialize)]
pub struct LangJobStatus {
    /// `idle` | `running` | `done` | `failed`.
    pub state: String,
    /// Labels translated + inserted so far.
    pub done: usize,
    /// Labels that need translating this run (English keys still missing).
    pub total: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Process-local map `lang -> status` for add-language jobs, held in `AppState`.
pub type LangJobMap = Arc<Mutex<HashMap<String, LangJobStatus>>>;

fn lang_daily_cap() -> u32 {
    std::env::var("I18N_LANG_DAILY_CAP")
        .ok()
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(DEFAULT_LANG_DAILY_CAP)
}

/// Consume one Gemini-call budget unit for today; `false` once the daily cap is
/// hit. Resets the counter at UTC midnight.
fn try_consume_lang_call(cap: u32) -> bool {
    let today = chrono::Utc::now().timestamp() / 86_400;
    let mut g = LANG_CAP.lock().unwrap();
    if g.0 != today {
        g.0 = today;
        g.1 = 0;
    }
    if g.1 >= cap {
        return false;
    }
    g.1 += 1;
    true
}

fn is_valid_lang(code: &str) -> bool {
    code.len() == 2 && code.bytes().all(|b| b.is_ascii_lowercase())
}

/// Serialize a status for a JSON body (explicit — no reliance on `json!` calling
/// `to_value` on a borrow).
fn status_json(s: &LangJobStatus) -> Value {
    let mut o = json!({ "state": s.state, "done": s.done, "total": s.total });
    if let Some(e) = &s.error {
        o["error"] = json!(e);
    }
    o
}

async fn set_status(map: &LangJobMap, lang: &str, s: LangJobStatus) {
    map.lock().await.insert(lang.to_string(), s);
}

#[derive(Debug, Deserialize)]
pub struct AddLangReq {
    pub lang: String,
}

/// POST /api/admin/i18n/languages { "lang": "fr" } — ADMIN ONLY.
///
/// Kicks off a background job that machine-translates every English `i18n_label`
/// into `lang` via Gemini and INSERTs the results using the SAME deterministic
/// record id (`label_record_id`) as the seed — so it's insert-if-missing,
/// idempotent, and cheap to re-run (already-present keys cost nothing).
/// Single-flight per lang: a second POST while one runs returns 409 with the
/// live status. Accept → 202 with the initial status.
pub async fn add_language(
    Extension(_claims): Extension<Claims>,
    State(state): State<Arc<AppState>>,
    Json(req): Json<AddLangReq>,
) -> (StatusCode, Json<Value>) {
    let lang = req.lang.trim().to_lowercase();
    if !is_valid_lang(&lang) {
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({
                "success": false,
                "error": "lang must be a 2-letter lowercase code (^[a-z]{2}$)",
                "code": "BAD_LANG",
            })),
        );
    }
    if lang == "en" {
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({
                "success": false,
                "error": "English is the base language and is always seeded",
                "code": "BASE_LANG",
            })),
        );
    }
    if !eck_core::ai::AiAuth::is_enabled_in_env() {
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(json!({
                "success": false,
                "error": "AI is not configured on this node — cannot machine-translate labels",
                "code": "AI_DISABLED",
            })),
        );
    }

    // Single-flight: reject (409) if a run for this lang is already in progress.
    {
        let mut jobs = state.i18n_lang_jobs.lock().await;
        if let Some(s) = jobs.get(&lang) {
            if s.state == "running" {
                return (
                    StatusCode::CONFLICT,
                    Json(json!({
                        "success": false,
                        "code": "IN_PROGRESS",
                        "lang": lang,
                        "status": status_json(s),
                    })),
                );
            }
        }
        jobs.insert(
            lang.clone(),
            LangJobStatus { state: "running".into(), done: 0, total: 0, error: None },
        );
    }

    let st = state.clone();
    let job_lang = lang.clone();
    tokio::spawn(async move {
        run_language_job(st, job_lang).await;
    });

    (
        StatusCode::ACCEPTED,
        Json(json!({
            "success": true,
            "lang": lang,
            "status": { "state": "running", "done": 0, "total": 0 },
        })),
    )
}

/// GET /api/admin/i18n/languages/:lang/status — ADMIN ONLY. Live status of an
/// add-language job from the in-memory map. Unknown lang → `idle`.
pub async fn add_language_status(
    Extension(_claims): Extension<Claims>,
    Path(lang): Path<String>,
    State(state): State<Arc<AppState>>,
) -> (StatusCode, Json<Value>) {
    let lang = lang.trim().to_lowercase();
    let status = {
        let jobs = state.i18n_lang_jobs.lock().await;
        jobs.get(&lang).cloned()
    }
    .unwrap_or(LangJobStatus { state: "idle".into(), done: 0, total: 0, error: None });
    (
        StatusCode::OK,
        Json(json!({ "success": true, "lang": lang, "status": status_json(&status) })),
    )
}

/// Background driver: translate all missing English labels into `lang`, updating
/// the shared status map as it goes and stamping the terminal state at the end.
async fn run_language_job(state: Arc<AppState>, lang: String) {
    let map = state.i18n_lang_jobs.clone();
    let fail = |done: usize, total: usize, err: String| LangJobStatus {
        state: "failed".into(),
        done,
        total,
        error: Some(err),
    };

    let http = match reqwest::Client::builder().timeout(Duration::from_secs(60)).build() {
        Ok(c) => c,
        Err(e) => {
            set_status(&map, &lang, fail(0, 0, format!("http client: {e}"))).await;
            return;
        }
    };
    let auth = match eck_core::ai::AiAuth::resolve(&http).await {
        Ok(a) if a.is_configured() => a,
        Ok(_) => {
            set_status(&map, &lang, fail(0, 0, "AI not configured".into())).await;
            return;
        }
        Err(e) => {
            set_status(&map, &lang, fail(0, 0, format!("AI auth: {e}"))).await;
            return;
        }
    };

    // English source labels (the base every language is translated from).
    let en_rows: Vec<Value> = match state
        .db
        .query("SELECT key, value FROM i18n_label WHERE lang = 'en'")
        .await
        .and_then(|mut r| r.take(0))
    {
        Ok(r) => r,
        Err(e) => {
            set_status(&map, &lang, fail(0, 0, format!("read en labels: {e}"))).await;
            return;
        }
    };

    // Keys already present for the target lang → skip (insert-if-missing). Makes
    // a re-run after a partial/failed job cheap and idempotent.
    let existing: Vec<String> = state
        .db
        .query("SELECT VALUE key FROM i18n_label WHERE lang = $lang")
        .bind(("lang", lang.clone()))
        .await
        .and_then(|mut r| r.take(0))
        .unwrap_or_default();
    let existing: HashSet<String> = existing.into_iter().collect();

    let mut missing: Vec<(String, String)> = Vec::new();
    for row in &en_rows {
        let (Some(k), Some(v)) = (
            row.get("key").and_then(|x| x.as_str()),
            row.get("value").and_then(|x| x.as_str()),
        ) else {
            continue;
        };
        if existing.contains(k) {
            continue;
        }
        missing.push((k.to_string(), v.to_string()));
    }
    let total = missing.len();
    if total == 0 {
        set_status(
            &map,
            &lang,
            LangJobStatus { state: "done".into(), done: 0, total: 0, error: None },
        )
        .await;
        tracing::info!("[i18n] language '{}' already complete — nothing to translate", lang);
        return;
    }
    set_status(
        &map,
        &lang,
        LangJobStatus { state: "running".into(), done: 0, total, error: None },
    )
    .await;

    let model_name =
        std::env::var("GEMINI_TRANSLATE_MODEL").unwrap_or_else(|_| DEFAULT_TRANSLATE_MODEL.to_string());
    let cap = lang_daily_cap();
    let target_name = crate::ai::translation::lang_display(&lang);

    let mut done = 0usize;
    for chunk in missing.chunks(LANG_CHUNK) {
        if !try_consume_lang_call(cap) {
            set_status(
                &map,
                &lang,
                fail(
                    done,
                    total,
                    format!(
                        "daily cap {cap} reached — {done} of {total} translated; re-run to finish"
                    ),
                ),
            )
            .await;
            tracing::warn!("[i18n] language '{}' hit daily cap after {} keys", lang, done);
            return;
        }

        // key -> English value JSON for this chunk (translate the VALUES).
        let mut obj = serde_json::Map::new();
        for (k, v) in chunk {
            obj.insert(k.clone(), Value::String(v.clone()));
        }
        let chunk_json = Value::Object(obj).to_string();

        let payload = json!({
            "contents": [{ "parts": [{ "text": build_label_prompt(&target_name, &chunk_json) }] }],
            "generationConfig": { "temperature": 0.1, "maxOutputTokens": 8192 },
        });

        let text = match auth.generate_content(&http, &model_name, payload).await {
            Ok((t, usage)) => {
                if !usage.is_null() {
                    crate::ai::telemetry::log_telemetry(
                        &state.db,
                        "i18n_label",
                        &model_name,
                        &format!("i18n:{lang}"),
                        &usage,
                    )
                    .await;
                }
                t
            }
            Err(e) => {
                // No retry (runaway guardrail): keep what's inserted, mark failed.
                set_status(&map, &lang, fail(done, total, format!("gemini: {e}"))).await;
                tracing::warn!("[i18n] language '{}' translation call failed: {e}", lang);
                return;
            }
        };

        let Some(parsed) = parse_label_json(&text) else {
            // Soft failure: skip this chunk (keys stay missing → next run retries).
            tracing::warn!(
                "[i18n] language '{}' — unparseable chunk response, skipping {} keys",
                lang,
                chunk.len()
            );
            continue;
        };

        // Only accept keys we asked for, with non-empty string translations.
        let mut rows: Vec<Value> = Vec::new();
        for (k, _) in chunk {
            if let Some(v) = parsed.get(k).and_then(|x| x.as_str()) {
                let v = v.trim();
                if v.is_empty() {
                    continue;
                }
                rows.push(json!({
                    "rid": label_record_id(&lang, k),
                    "key": k,
                    "lang": lang,
                    "value": v,
                }));
            }
        }
        if !rows.is_empty() {
            let n = rows.len();
            match state
                .db
                .query(
                    "FOR $r IN $rows { \
                         CREATE type::record('i18n_label', $r.rid) CONTENT { \
                             key: $r.key, lang: $r.lang, value: $r.value, updated_at: time::now() \
                         }; \
                     }",
                )
                .bind(("rows", rows))
                .await
            {
                Ok(_) => done += n,
                Err(e) => tracing::warn!("[i18n] language '{}' insert failed: {e}", lang),
            }
        }

        set_status(
            &map,
            &lang,
            LangJobStatus { state: "running".into(), done, total, error: None },
        )
        .await;
        tokio::time::sleep(Duration::from_millis(200)).await;
    }

    if done == 0 {
        set_status(
            &map,
            &lang,
            fail(0, total, "no labels were translated (all chunks failed to parse)".into()),
        )
        .await;
        tracing::warn!("[i18n] language '{}' produced no usable translations", lang);
    } else {
        set_status(
            &map,
            &lang,
            LangJobStatus { state: "done".into(), done, total, error: None },
        )
        .await;
        // Nudge open clients to refresh their available-locale set.
        let _ = state.ws_tx.send(
            json!({ "type": "i18n_language_ready", "lang": lang, "done": done, "total": total })
                .to_string(),
        );
        tracing::info!("[i18n] language '{}' translated {} of {} labels", lang, done, total);
    }
}

/// Prompt for a chunk: translate the VALUES of a JSON object into `target_name`,
/// preserving keys, `{placeholders}`, HTML tags and technical identifiers, and
/// returning a raw JSON object.
fn build_label_prompt(target_name: &str, chunk_json: &str) -> String {
    format!(
        "You are a professional software localizer. Translate the VALUES of the JSON object \
         below into {target}.\n\
         Rules:\n\
         - Return ONLY a JSON object with the SAME keys; replace each value with its {target} \
           translation. Do not add, drop, or reorder keys.\n\
         - Preserve interpolation placeholders like {{name}}, {{count}}, {{year}} VERBATIM \
           (identical braces and identifier).\n\
         - Preserve HTML tags such as <strong>…</strong> and their nesting.\n\
         - Do NOT translate technical identifiers: product/brand names (eckWMS, Odoo, Rust, \
           SvelteKit), URLs, and email addresses — copy them verbatim.\n\
         - Output raw JSON only: no markdown fences, no commentary.\n\n\
         JSON:\n{json}",
        target = target_name,
        json = chunk_json,
    )
}

/// Parse Gemini's chunk reply into a `{key: value}` map, tolerating ```json
/// fences and stray prose around the object. `None` if no JSON object is found.
fn parse_label_json(text: &str) -> Option<serde_json::Map<String, Value>> {
    let t = text.trim();
    let t = t.strip_prefix("```json").or_else(|| t.strip_prefix("```")).unwrap_or(t);
    let t = t.strip_suffix("```").unwrap_or(t).trim();
    if let Ok(Value::Object(m)) = serde_json::from_str::<Value>(t) {
        return Some(m);
    }
    // Fallback: slice from the first '{' to the last '}'.
    let start = t.find('{')?;
    let end = t.rfind('}')?;
    if end <= start {
        return None;
    }
    match serde_json::from_str::<Value>(&t[start..=end]) {
        Ok(Value::Object(m)) => Some(m),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The baked-in seed must parse, be non-empty, and carry no duplicate
    /// (lang, key) pairs — otherwise the deterministic record id would make two
    /// seed rows fight for one DB row.
    #[test]
    fn baked_seed_parses_and_is_unique() {
        let entries = parse_seed(I18N_SEED_JSON).expect("seed JSON must parse");
        assert!(!entries.is_empty(), "seed should not be empty");
        let mut pairs = HashSet::new();
        for e in &entries {
            assert!(!e.key.is_empty() && !e.lang.is_empty());
            assert!(
                pairs.insert((e.lang.clone(), e.key.clone())),
                "duplicate (lang,key) in seed: {} {}",
                e.lang,
                e.key
            );
        }
    }

    /// dedup collapses a repeated (lang, key) onto one deterministic id (first
    /// wins) while keeping genuinely distinct rows.
    #[test]
    fn dedup_collapses_by_record_id() {
        let entries = vec![
            SeedEntry { key: "shell.a".into(), lang: "de".into(), value: "A1".into() },
            SeedEntry { key: "shell.a".into(), lang: "de".into(), value: "A2".into() }, // dup
            SeedEntry { key: "shell.a".into(), lang: "en".into(), value: "A".into() },
            SeedEntry { key: "shell.b".into(), lang: "de".into(), value: "B".into() },
        ];
        let out = dedup_seed(entries);
        assert_eq!(out.len(), 3, "one (de, shell.a) dup removed");
        // First wins.
        let de_a = out.iter().find(|(_, e)| e.lang == "de" && e.key == "shell.a").unwrap();
        assert_eq!(de_a.1.value, "A1");
        // Each retained row's id matches the deterministic derivation.
        for (rid, e) in &out {
            assert_eq!(*rid, label_record_id(&e.lang, &e.key));
        }
    }

    /// The seed diff: insert missing, update drifted, keep `src:'user'`,
    /// leave matching rows untouched.
    #[test]
    fn seed_actions_partitions_correctly() {
        let entry = |key: &str, value: &str| SeedEntry {
            key: key.into(),
            lang: "en".into(),
            value: value.into(),
        };
        let rows = vec![
            ("r_missing".to_string(), entry("a.missing", "new")),
            ("r_same".to_string(), entry("a.same", "kept")),
            ("r_stale".to_string(), entry("a.stale", "current")),
            ("r_stale_seed".to_string(), entry("a.stale_seed", "current")),
            ("r_user".to_string(), entry("a.user", "current")),
        ];
        let existing: HashMap<String, (Option<String>, Option<String>)> = [
            ("r_same".to_string(), (Some("kept".to_string()), None)),
            // Legacy row (no src) whose value drifted → adopted + updated.
            ("r_stale".to_string(), (Some("old".to_string()), None)),
            ("r_stale_seed".to_string(), (Some("old".to_string()), Some("seed".to_string()))),
            ("r_user".to_string(), (Some("edited".to_string()), Some("user".to_string()))),
        ]
        .into_iter()
        .collect();

        let (inserts, updates, kept_user) = seed_actions(&rows, &existing);
        assert_eq!(inserts.len(), 1);
        assert_eq!(inserts[0]["rid"], "r_missing");
        let update_ids: Vec<&str> = updates.iter().map(|u| u["rid"].as_str().unwrap()).collect();
        assert_eq!(update_ids, vec!["r_stale", "r_stale_seed"]);
        assert!(updates.iter().all(|u| u["value"] == "current"));
        assert_eq!(kept_user, 1);
    }

    #[test]
    fn valid_lang_is_two_lowercase_letters() {
        assert!(is_valid_lang("fr"));
        assert!(is_valid_lang("ko"));
        assert!(!is_valid_lang("FR")); // must be lowercase
        assert!(!is_valid_lang("f")); // too short
        assert!(!is_valid_lang("fra")); // too long
        assert!(!is_valid_lang("f1")); // must be letters
        assert!(!is_valid_lang(""));
    }

    #[test]
    fn parse_label_json_handles_fences_and_prose() {
        // Bare object.
        let m = parse_label_json(r#"{"a":"1","b":"2"}"#).unwrap();
        assert_eq!(m.get("a").unwrap().as_str(), Some("1"));
        // Fenced.
        let m = parse_label_json("```json\n{\"a\":\"x\"}\n```").unwrap();
        assert_eq!(m.get("a").unwrap().as_str(), Some("x"));
        // Prose around the object.
        let m = parse_label_json("Sure! Here you go:\n{\"a\":\"y\"}\nHope that helps.").unwrap();
        assert_eq!(m.get("a").unwrap().as_str(), Some("y"));
        // No object at all.
        assert!(parse_label_json("no json here").is_none());
    }

    #[test]
    fn label_prompt_keeps_placeholders_and_names_language() {
        let p = build_label_prompt("French", r#"{"greet":"Hello {name}"}"#);
        assert!(p.contains("French"));
        assert!(p.contains("{name}")); // {{name}} in source renders as {name}
        assert!(p.contains(r#""greet":"Hello {name}""#));
    }
}
