//! `GET /api/admin/mcp-connector` — hands an admin a ready-to-run MCP connector
//! bundle (zip) for the WMS business-graph surface.
//!
//! The server already speaks MCP on `POST /mcp` (bearer-gated, Master vs Agent
//! tier) and ships a client-side stdio bridge, `eck-mcp-shim`, whose free
//! *direct* mode is configured by a `shim.env` next to the exe. Rather than make
//! every operator hand-assemble that, this endpoint bakes a bundle server-side:
//! the shim binary for the requested platform, a `shim.env` pre-filled with THIS
//! node's base URL + the tier's bearer, and a README covering both the native
//! remote-MCP path and the bundled-shim stdio path.
//!
//! Admin-gated: mounted in the admin router (JWT + role=admin), so the caller is
//! already a trusted operator when we mint a bundle carrying a live token. The
//! token is written into the zip on purpose (that IS the connector) but is NEVER
//! logged.

use std::collections::HashMap;
use std::io::Write as _;
use std::path::PathBuf;

use axum::{
    extract::Query,
    http::{header, HeaderMap, StatusCode},
    response::{IntoResponse, Response},
    Json,
};
use serde_json::json;

/// `{"error": "..."}` with a status — the uniform failure shape for this route.
fn err(status: StatusCode, msg: impl Into<String>) -> Response {
    (status, Json(json!({ "error": msg.into() }))).into_response()
}

/// Resolve the bearer for the requested tier from the SAME env vars
/// `super::authenticate` reads. Empty/unset → an actionable 400 naming the var.
fn resolve_token(master: bool) -> Result<String, Response> {
    if master {
        let token = std::env::var("ECK_MCP_MASTER_TOKEN")
            .ok()
            .filter(|s| !s.trim().is_empty())
            .or_else(|| {
                std::env::var("XELIXIR_SERVICE_TOKEN")
                    .ok()
                    .filter(|s| !s.trim().is_empty())
            })
            .unwrap_or_default();
        if token.trim().is_empty() {
            return Err(err(
                StatusCode::BAD_REQUEST,
                "master tier token is not configured on this node — set ECK_MCP_MASTER_TOKEN \
                 (or XELIXIR_SERVICE_TOKEN) before generating a master connector",
            ));
        }
        Ok(token)
    } else {
        let token = std::env::var("ECK_MCP_AGENT_TOKEN").unwrap_or_default();
        if token.trim().is_empty() {
            return Err(err(
                StatusCode::BAD_REQUEST,
                "agent tier token is not configured on this node — set ECK_MCP_AGENT_TOKEN \
                 before generating an agent connector",
            ));
        }
        Ok(token)
    }
}

/// `<scheme>://<host>` for the client: scheme from `X-Forwarded-Proto` (else
/// `http`), host from `Host`; if `Host` is absent fall back to env `BASE_URL`;
/// both absent → 400.
fn resolve_base_url(headers: &HeaderMap) -> Result<String, Response> {
    let scheme = headers
        .get("x-forwarded-proto")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.split(',').next())
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .unwrap_or("http")
        .to_string();
    let host = headers
        .get(header::HOST)
        .and_then(|v| v.to_str().ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    if let Some(host) = host {
        return Ok(format!("{scheme}://{host}"));
    }
    let base = std::env::var("BASE_URL")
        .ok()
        .map(|s| s.trim().trim_end_matches('/').to_string())
        .filter(|s| !s.is_empty());
    match base {
        Some(b) => Ok(b),
        None => Err(err(
            StatusCode::BAD_REQUEST,
            "cannot determine the base URL for the client — no Host header on the request \
             and BASE_URL is unset",
        )),
    }
}

/// Truthy query flag: `1` / `true` (case-insensitive).
fn is_truthy(v: Option<&String>) -> bool {
    matches!(
        v.map(|s| s.trim().to_ascii_lowercase()).as_deref(),
        Some("1") | Some("true")
    )
}

/// The `shim.env` written next to the shim binary — EXACT format the shim's
/// direct mode expects. Token is embedded on purpose; never logged.
fn shim_env(base_url: &str, token: &str) -> String {
    format!(
        "# 9eck WMS MCP connector — generated by the server, keep this file next to the shim binary\n\
         ECK_SHIM_MODE=direct\n\
         ECK_SHIM_URL={base_url}\n\
         ECK_SHIM_BEARER={token}\n"
    )
}

/// The bundle README. English; both connection paths + the PII paragraph.
fn readme(base_url: &str, token: &str, bin_name: &str) -> String {
    format!(
        "# 9eck WMS MCP connector\n\
\n\
This bundle connects an MCP client to the 9eck WMS business-graph surface\n\
(customers, tickets, devices, warehouse). Pick ONE of the two paths below.\n\
\n\
## Option A — native remote MCP (preferred, for clients that support HTTP transport)\n\
\n\
```\n\
claude mcp add --transport http 9eck-wms {base_url}/mcp --header \"Authorization: Bearer {token}\"\n\
```\n\
\n\
Any client that speaks the MCP Streamable-HTTP transport can point straight at\n\
`{base_url}/mcp` with that `Authorization: Bearer` header — no local process needed.\n\
\n\
## Option B — stdio bridge (bundled `{bin_name}`)\n\
\n\
For clients that only launch a local `command` MCP server (e.g. Antigravity /\n\
Gemini), run the bundled `{bin_name}`. It auto-loads `shim.env` from its own\n\
directory, so keep the two files side by side — no arguments or extra config.\n\
\n\
Sample `mcp_config.json` snippet (replace the command with the ABSOLUTE path to\n\
the shim binary you unpacked):\n\
\n\
```json\n\
{{\"mcpServers\":{{\"9eck-wms\":{{\"command\":\"<absolute path to {bin_name}>\"}}}}}}\n\
```\n\
\n\
## PII\n\
\n\
PII (names, emails, phones, addresses) is NEVER returned in clear on this\n\
surface: it comes back as stable pseudonym tokens (`Name_<hex>`, `Email_<hex>`,\n\
`Phone_<hex>`, `Address_<hex>`, and `Company_<hex>` inside AI-summary text). A\n\
master-tier user restores the real values INTO A FILE — write your report to a\n\
file, then call the shim's `reveal_file` tool on its path when the file is on\n\
your own machine, or the server tool `reveal_file_local` when the file lives on\n\
the WMS server machine (same host / shared disk). The revealed values are\n\
written to disk only — never back into the model's context.\n"
    )
}

/// `GET /api/admin/mcp-connector` — see module docs. Admin-gated by the router.
pub(crate) async fn mcp_connector(
    headers: HeaderMap,
    Query(params): Query<HashMap<String, String>>,
) -> Response {
    // ── platform (required) ──
    let platform = match params.get("platform").map(|s| s.trim()) {
        Some("windows") => "windows",
        Some("linux") => "linux",
        _ => {
            return err(
                StatusCode::BAD_REQUEST,
                "query param `platform` is required and must be `windows` or `linux`",
            )
        }
    };
    let is_windows = platform == "windows";

    // ── tier (optional, default agent) ──
    let master = match params.get("tier").map(|s| s.trim()) {
        None | Some("") | Some("agent") => false,
        Some("master") => true,
        Some(other) => {
            return err(
                StatusCode::BAD_REQUEST,
                format!("query param `tier` must be `agent` or `master`, got `{other}`"),
            )
        }
    };
    let config_only = is_truthy(params.get("config_only"));

    // ── resolve the pieces (any failure → JSON error) ──
    let token = match resolve_token(master) {
        Ok(t) => t,
        Err(e) => return e,
    };
    let base_url = match resolve_base_url(&headers) {
        Ok(b) => b,
        Err(e) => return e,
    };

    // ── shim binary lookup ──
    let dist_dir: PathBuf = std::env::var("ECK_SHIM_DIST_DIR")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            std::env::current_exe()
                .ok()
                .and_then(|p| p.parent().map(|d| d.to_path_buf()))
                .unwrap_or_else(|| PathBuf::from("."))
                .join("shim-dist")
        });
    let bin_name = if is_windows {
        "eck-mcp-shim.exe"
    } else {
        "eck-mcp-shim"
    };
    let bin_path = dist_dir.join(bin_name);

    let binary: Option<Vec<u8>> = if config_only {
        None
    } else {
        match std::fs::read(&bin_path) {
            Ok(b) => Some(b),
            Err(_) => {
                return err(
                    StatusCode::SERVICE_UNAVAILABLE,
                    format!(
                        "shim binary not found at {} — place the {} binary in that directory \
                         (set ECK_SHIM_DIST_DIR to relocate), or retry with config_only=1 to \
                         omit the binary from the bundle",
                        bin_path.display(),
                        bin_name
                    ),
                )
            }
        }
    };

    // ── assemble the zip in memory ──
    let env_file = shim_env(&base_url, &token);
    let readme_file = readme(&base_url, &token, bin_name);
    let zip_bytes = match build_zip(binary.as_deref(), bin_name, &env_file, &readme_file, !is_windows) {
        Ok(b) => b,
        Err(e) => {
            return err(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("failed to assemble connector bundle: {e}"),
            )
        }
    };

    let filename = format!("9eck-mcp-connector-{platform}.zip");
    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "application/zip".to_string()),
            (
                header::CONTENT_DISPOSITION,
                format!("attachment; filename=\"{filename}\""),
            ),
        ],
        zip_bytes,
    )
        .into_response()
}

/// Build the connector zip in memory. When `unix_exec` the shim binary entry is
/// stored with mode 0o755 so the exec bit survives unzip on Linux.
fn build_zip(
    binary: Option<&[u8]>,
    bin_name: &str,
    env_file: &str,
    readme_file: &str,
    unix_exec: bool,
) -> std::io::Result<Vec<u8>> {
    use zip::write::FileOptions;

    let mut cursor = std::io::Cursor::new(Vec::new());
    {
        let mut zip = zip::ZipWriter::new(&mut cursor);
        let text_opts = FileOptions::default().compression_method(zip::CompressionMethod::Deflated);

        if let Some(bytes) = binary {
            let bin_opts = if unix_exec {
                FileOptions::default()
                    .compression_method(zip::CompressionMethod::Deflated)
                    .unix_permissions(0o755)
            } else {
                FileOptions::default().compression_method(zip::CompressionMethod::Deflated)
            };
            zip.start_file(bin_name, bin_opts)?;
            zip.write_all(bytes)?;
        }

        zip.start_file("shim.env", text_opts)?;
        zip.write_all(env_file.as_bytes())?;

        zip.start_file("README.md", text_opts)?;
        zip.write_all(readme_file.as_bytes())?;

        zip.finish()?;
    }
    Ok(cursor.into_inner())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base_url_from_host_and_scheme() {
        let mut h = HeaderMap::new();
        h.insert(header::HOST, "wms.example.com".parse().unwrap());
        h.insert("x-forwarded-proto", "https".parse().unwrap());
        assert_eq!(resolve_base_url(&h).unwrap(), "https://wms.example.com");
    }

    #[test]
    fn base_url_defaults_scheme_to_http() {
        let mut h = HeaderMap::new();
        h.insert(header::HOST, "10.0.0.5:3210".parse().unwrap());
        assert_eq!(resolve_base_url(&h).unwrap(), "http://10.0.0.5:3210");
    }

    #[test]
    fn truthy_flag() {
        assert!(is_truthy(Some(&"1".to_string())));
        assert!(is_truthy(Some(&"true".to_string())));
        assert!(is_truthy(Some(&"TRUE".to_string())));
        assert!(!is_truthy(Some(&"0".to_string())));
        assert!(!is_truthy(None));
    }

    #[test]
    fn shim_env_exact_format() {
        let env = shim_env("https://h.de", "tok123");
        assert_eq!(
            env,
            "# 9eck WMS MCP connector — generated by the server, keep this file next to the shim binary\n\
             ECK_SHIM_MODE=direct\n\
             ECK_SHIM_URL=https://h.de\n\
             ECK_SHIM_BEARER=tok123\n"
        );
    }

    #[test]
    fn zip_contains_expected_entries() {
        let bytes = build_zip(Some(b"BINARY"), "eck-mcp-shim", "ENV", "README", true).unwrap();
        let reader = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let names: Vec<String> = reader.file_names().map(String::from).collect();
        assert!(names.contains(&"eck-mcp-shim".to_string()));
        assert!(names.contains(&"shim.env".to_string()));
        assert!(names.contains(&"README.md".to_string()));
    }

    #[test]
    fn zip_config_only_omits_binary() {
        let bytes = build_zip(None, "eck-mcp-shim", "ENV", "README", true).unwrap();
        let reader = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let names: Vec<String> = reader.file_names().map(String::from).collect();
        assert!(!names.iter().any(|n| n == "eck-mcp-shim"));
        assert!(names.contains(&"shim.env".to_string()));
    }
}
